#!/usr/bin/env bash
export DISPLAY=${DISPLAY:-:0}
export XAUTHORITY=${XAUTHORITY:-$HOME/.Xauthority}
export PATH=/usr/local/bin:/usr/bin:/bin:$HOME/bin:$PATH
exec /usr/bin/env python3 /home/$USER/bin/gui.py